import { chromium } from 'playwright';
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 430, height: 932 } });
await page.goto('http://localhost:5173', { waitUntil: 'networkidle' });
await page.screenshot({ path: 'screenshot-mobile.png', fullPage: true });
await page.setViewportSize({ width: 1440, height: 900 });
await page.goto('http://localhost:5173', { waitUntil: 'networkidle' });
await page.screenshot({ path: 'screenshot-desktop.png', fullPage: true });
await browser.close();
console.log('Done');
